# action.yml
name: 'Betterscan Action'
description: 'Betterscan Action'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Create folder
        run: |
        mkdir .checkmate
    - name: Store state
      uses: actions/upload-artifact@v2
      with:
        name: state
        path: .checkmate
    - name: Get state
      uses: actions/download-artifact@v2
      with:
        name: state
    - name: Betterscan Scan
      uses: topcodersonline/betterscan@v3
    - name: Store state
      uses: actions/upload-artifact@v2
      with:
        name: state
        path: .checkmate
branding:
  icon: 'award'  
  color: 'green'
  
